# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dante/Documents/handtrack/htrack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dante/Documents/handtrack/htrack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dante/Documents/handtrack/htrack/CMakeFiles /home/dante/Documents/handtrack/htrack/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dante/Documents/handtrack/htrack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named util_headers

# Build rule for target.
util_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_headers
.PHONY : util_headers

# fast build rule for target.
util_headers/fast:
	$(MAKE) -f util/CMakeFiles/util_headers.dir/build.make util/CMakeFiles/util_headers.dir/build
.PHONY : util_headers/fast

#=============================================================================
# Target rules for targets named cudax_files

# Build rule for target.
cudax_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudax_files
.PHONY : cudax_files

# fast build rule for target.
cudax_files/fast:
	$(MAKE) -f cudax/CMakeFiles/cudax_files.dir/build.make cudax/CMakeFiles/cudax_files.dir/build
.PHONY : cudax_files/fast

#=============================================================================
# Target rules for targets named cudax

# Build rule for target.
cudax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudax
.PHONY : cudax

# fast build rule for target.
cudax/fast:
	$(MAKE) -f cudax/CMakeFiles/cudax.dir/build.make cudax/CMakeFiles/cudax.dir/build
.PHONY : cudax/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) -f tracker/CMakeFiles/shaders.dir/build.make tracker/CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named htracksdk

# Build rule for target.
htracksdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htracksdk
.PHONY : htracksdk

# fast build rule for target.
htracksdk/fast:
	$(MAKE) -f tracker/CMakeFiles/htracksdk.dir/build.make tracker/CMakeFiles/htracksdk.dir/build
.PHONY : htracksdk/fast

#=============================================================================
# Target rules for targets named htrack_atb

# Build rule for target.
htrack_atb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htrack_atb
.PHONY : htrack_atb

# fast build rule for target.
htrack_atb/fast:
	$(MAKE) -f apps/htrack_atb/CMakeFiles/htrack_atb.dir/build.make apps/htrack_atb/CMakeFiles/htrack_atb.dir/build
.PHONY : htrack_atb/fast

#=============================================================================
# Target rules for targets named htrack_qt

# Build rule for target.
htrack_qt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htrack_qt
.PHONY : htrack_qt

# fast build rule for target.
htrack_qt/fast:
	$(MAKE) -f apps/htrack_qt/CMakeFiles/htrack_qt.dir/build.make apps/htrack_qt/CMakeFiles/htrack_qt.dir/build
.PHONY : htrack_qt/fast

#=============================================================================
# Target rules for targets named colorpick

# Build rule for target.
colorpick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 colorpick
.PHONY : colorpick

# fast build rule for target.
colorpick/fast:
	$(MAKE) -f apps/colorpick/CMakeFiles/colorpick.dir/build.make apps/colorpick/CMakeFiles/colorpick.dir/build
.PHONY : colorpick/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... util_headers"
	@echo "... cudax_files"
	@echo "... cudax"
	@echo "... shaders"
	@echo "... htracksdk"
	@echo "... htrack_atb"
	@echo "... htrack_qt"
	@echo "... colorpick"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

