set(freenect2_DIR ~/freenect2/lib/cmake/freenect2)
add_compile_options(-std=c++11)
add_definitions(-std=c++11)
find_package(freenect2 REQUIRED)
include_directories("/usr/include/libusb-1.0/")
INCLUDE_DIRECTORIES(${freenect2_INCLUDE_DIR})
#message("freenect2_LIBRARIES = ${freenect2_LIBRARIES}")
list(APPEND LIBRARIES ${freenect2_LIBRARIES})
add_definitions(-DHAS_LIBFREENECT)
